// generated by stringer -type tokenType; DO NOT EDIT

package tokenizer

import "fmt"

const _tokenType_name = "IdentAtKeywordStringBadStringBadUriBadCommentHashNumberPercentageDimensionUriUnicodeRangeCDOCDCColonSemicolonCommaLBraceRBraceLParenRParenLBracketRBracketIncludesPrefixmatchSuffixmatchDashmatchCommentFunctionDelimSubstringMatchColumnWS"

var _tokenType_index = [...]uint8{0, 5, 14, 20, 29, 35, 45, 49, 55, 65, 74, 77, 89, 92, 95, 100, 109, 114, 120, 126, 132, 138, 146, 154, 162, 173, 184, 193, 200, 208, 213, 227, 233, 235}

func (i tokenType) String() string {
	if i < 0 || i+1 >= tokenType(len(_tokenType_index)) {
		return fmt.Sprintf("tokenType(%d)", i)
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
