# defines $GC) (compiler), $(LD) (linker) and $(O) (architecture)
include $(GOROOT)/src/Make.inc

TARG=html/trans
GOFILES=\
	html/transform/tree.go\
	html/transform/selector.go\
	#html/trans/transform.go\

include $(GOROOT)/src/Make.pkg
